name: build and test matrix multiplication

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
        - name: checkout repository
          uses: actions/checkout@v4
          with:
            submodules: recursive

        - name: set up environment
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake libopenmpi-dev

        - name: build project
          run: |
            mkdir build
            cd build
            cmake ..
            cmake --build .

        - name: run tests
          run: |
            cd build
            ctest --output-on-failure --output-log test_results.xml

        - name: upload test results
          if: failure()
          uses: actions/upload-artifact@v4
          with:
            name: test-results
            path: build/test_results.xml

    build-singularity:
        needs: build-and-test
        runs-on: ubuntu-latest

        steps:
        - name: checkout repository
          uses: actions/checkout@v4
          with:
            submodules: recursive

        - name: set up environment
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake libopenmpi-dev

        - name: install Singularity         
          uses: eWaterCycle/setup-singularity@v7
          with:
            singularity-version: 3.8.0
            
        - name: Build Singularity Image
          run: |
            singularity build --fakeroot matrix_multiplication.sif sweng_project2.def
            
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: matrix_multiplication
            path: matrix_multiplication.sif
        # install sshpass
        - name: Install sshpass
          run: |
            sudo apt-get install sshpass 
        # scp the singularity file into GUSER@SSH_GALIELO using SSH_PASS secret
        - name: Upload Singularity Image
          run: |
            sshpass -p ${{ secrets.SSH_PASS }} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null matrix_multiplication.sif job.sh matrixA.txt matrixB.txt ${{ vars.GUSER }}@${{ vars.SSH_GALILEO }}:/g100/home/usertrain/a08trb46/
        # using ssh run the job.sh script
        - name: Run Job
          run: |
            sshpass -p ${{ secrets.SSH_PASS }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ vars.GUSER }}@${{ vars.SSH_GALILEO }} 'rm -rf mpi_singularity_error.txt mpi_singularity_output.txt'
            sshpass -p ${{ secrets.SSH_PASS }} ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ vars.GUSER }}@${{ vars.SSH_GALILEO }} 'sbatch --wait' < job.sh
        # scp the output files back to the runner
        - name: Download Output
          run: |
            sshpass -p ${{ secrets.SSH_PASS }} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ vars.GUSER }}@${{ vars.SSH_GALILEO }}:/g100/home/usertrain/a08trb46/mpi_singularity_error.txt .
            sshpass -p ${{ secrets.SSH_PASS }} scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ${{ vars.GUSER }}@${{ vars.SSH_GALILEO }}:/g100/home/usertrain/a08trb46/mpi_singularity_output.txt .
            echo "Error file:"
            cat mpi_singularity_error.txt
            echo "Output file:"
            cat mpi_singularity_output.txt
        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: matrix_multiplication_output
            path: mpi_singularity_error.txt mpi_singularity_output.txt

