name: build and test matrix multiplication

on:
    push:
        branches:
        - main
        - Luca
    pull_request:
        branches:
        - main
        - Luca

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
        - name: checkout repository
          uses: actions/checkout@v4
          with:
            submodules: recursive

        - name: set up environment
          run: |
            sudo apt-get update
            sudo apt-get install -y build-essential cmake mpich libmpich-dev
            sudo apt-get install -y gpg-agent software-properties-common
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E19D9B5B9C19E955
            sudo add-apt-repository "deb [arch=amd64] http://repo.sylabs.io/sciniviz/ppa/ jammy main"
            sudo apt-get update
            sudo apt-get install -y singularity-container

        - name: build project
          run: |
            mkdir build
            cd build
            cmake ..
            cmake --build .

        - name: run tests
          run: |
            cd build
            ctest --output-on-failure --output-log test_results.xml

        - name: upload test results
          if: failure()
          uses: actions/upload-artifact@v4
          with:
            name: test-results
            path: build/test_results.xml
        
        - name: Build Singularity Image
          run: |
            sudo apt-get update
            sudo apt-get install -y singularity-container
            sudo singularity build matrix_multiplication.sif sweng_project2.def
            
        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: matrix_multiplication
            path: matrix_multiplication.sif

        name: CI

